title: Zxiro Website
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zxiro.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Zxiro'
  last_name: 'Yang'
  cv: '//www.linkedin.com/in/zih-you-yang/'
  avatar: '/images/avatar.svg'
  github_username: Zxiro
  email: zxirocon@gmail.com 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


